# Generated by Django 3.1.5 on 2021-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
