# Generated by Django 3.1.5 on 2021-01-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20210113_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='default_exercise.png', upload_to='exercise_pics'),
        ),
    ]
