# Generated by Django 3.1.5 on 2021-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercisestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='contents',
            field=models.ManyToManyField(to='exercises.ExerciseStats'),
        ),
    ]
