# Generated by Django 3.1.5 on 2021-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_exercisestats_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestats',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
