# Generated by Django 3.1.5 on 2021-01-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20210119_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestats',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
