# Generated by Django 3.1.5 on 2021-01-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_remove_exercisestats_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestats',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
