# Generated by Django 3.1.5 on 2021-01-19 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_exercisestats_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestats',
            name='time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='exercisestats',
            name='reps',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercisestats',
            name='sets',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
