# Generated by Django 3.1.5 on 2021-01-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_auto_20210119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisestats',
            name='reps',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='exercisestats',
            name='sets',
            field=models.PositiveIntegerField(blank=True, default=3),
        ),
    ]
